### ISSUE TITLE
Updating Dotmatrix for 2018

### ISSUE THREAD

**Issue by avogel3** [hashrocket/dotmatrix#71]
At the Hashrocket Miniconf of 2018, fellow rocketeers and I proclaimed a renewed interest in the development of dotmatrix. Right now, we feel we have neglected this project simply because 'it just works'. Starting in 2018, we are actively looking to refactor parts of dotmatrix: removing anything deprecated or no longer in use and adding more relevant tooling.  

With that being said, we are interested in input from the community and original contributors that helped build this tool. Please feel free to drop a comment on what you would like to see in 'dotmatrix2018'. 

Thanks!

**Comment by plicjo** [comment]
When you type “mux” inside of a project, I have to restart VIM because it
bugs out on the initial load.

**Comment by plicjo** [comment]
An option for dotmatrix to overwrite your configuration files: `.bashrc` and `.zshrc`, etc, would also be amazing.

Currently, if it sees the files there, it just leaves them alone. When you guys update those files, we don't get the updates on `hr update`, as it won't overwrite the file.

It would be cool to pass a flag, allowing dotmatrix to update the system configuration files.

**Comment by mattpolito** [comment]
This appears to be a great base (https://github.com/tmux-plugins/tmux-sensible) that would probably remove/cleanup the existing tmux config.

**Comment by mattpolito** [comment]
@plicjo As far as overwriting dot files... are you referring to a flag that would blow away the existing files that are being skipped?

**Comment by plicjo** [comment]
@mattpolito Yep!

**Comment by BrandonShega** [comment]
It's awesome that you guys are still maintaining this, I use it to set up all of my machines.  I've created a fork and basically changed everything to my own personal stuff rather than using locals so when you guys update this I just merge with mine so I hope it doesn't change too drastically :).  So far I've been able to keep up fairly well.  Otherwise, I've been loving this it makes it so easy to get my exact setup across multiple machines.

Have you guys thought about any kind of `brew` implementation with a `Brewfile` to automatically install dependencies?
